name: Upload
on: ['push']
jobs:
       upload:
             runs-on: ubuntu-latest
             steps:
               - name: Checkout
                 uses: actions/checkout@v2
               - name: Set up Node.JS
                 uses: actions/setup-node@v2
                 with:
                    node-version: '14'
                 
               - name: Load key
                 working-directory: ${{github.workspace}}
                 env:
                    VANIKEY: ${{ secrets.VANIKEY }}
                 run: |
                    echo "$VANIKEY">~/vanikey
                    mkdir -p ~/.ssh
                    printf "StrictHostKeyChecking no\nUserKnownHostsFile /dev/null">~/.ssh/config
                    chmod 0600 ~/vanikey
               - name: Fetch current whitelist
                 working-directory: ${{github.workspace}}
                 run: |
                    echo "${{secrets.FETCHWHITELISTBATCH}}">~/a
                    sftp -i ~/vanikey -b ~/a ${{secrets.VANIWORLDSERVER}}
               - name: Process file
                 working-directory: ${{github.workspace}}
                 run: node convert.js
               - name: Upload and execute remote commands
                 working-directory: ${{github.workspace}}
                 run: |
                    echo "${{secrets.UPLOADWHITELISTBATCH}}">~/a
                    sftp -i ~/vanikey -b ~/a vaniworld@vani.world
                    ssh -i ~/vanikey vaniworld@vani.world "${{secrets.SERVERPEERCMDS}}"